version: "3.9"

x-app:
  &default-app
  image: shadowsocks/shadowsocks-libev
  network_mode: host
  privileged: true
  restart: always
  dns:
    - 1.1.1.1
    - 8.8.8.8
  logging:
    driver: "json-file"
    options:
      max-size: "100k"
      max-file: "1"

services:
  shadowsocks:
    <<: *default-app
    container_name: shadowsocks
    env_file: .env
