version: "3.9"

x-app:
  &default-app
  image: c18s/activemq
  network_mode: bridge
  privileged: true
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "100k"
      max-file: "1"

services:
  activemq-classic:
    <<: *default-app
    container_name: activemq-classic
    env_file: .env
    ports:
      - "1883:1883"
      - "5672:5672"
      - "8161:8161"
      - "61613:61613"
      - "61614:61614"
      - "61616:61616"
    volumes:
      - "./data:/opt/activemq/data"
