version: "3.9"

x-app: &default-app
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "100k"
      max-file: "1"

services:
  redis:
    <<: *default-app
    image: bitnami/redis:6.2
    container_name: redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
      - REDIS_DISABLE_COMMANDS=${REDIS_DISABLE_COMMANDS:-FLUSHDB,FLUSHALL}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
    volumes:
      - "./data:/bitnami/redis/data"
